[project]
name = "ts-bot"
version = "0.1.0"
description = "a trouble shoting bot"
authors = [
    {name = "Warrior",email = "kichuasejaina@gmail.com"}
]
license = {text = "GNU Open"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dask[complete] (>=2025.11.0,<2026.0.0)",
    "pylint (>=4.0.3,<5.0.0)",
    "pydantic (>=2.12.5,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
